import { useNavigate } from 'react-router-dom'
const N='#0D1B3E',B='#2563EB',SL='#475569'
const VID='1180620888'
const LOGO=()=>(<div style={{display:'flex',alignItems:'center',gap:10}}><svg width="34" height="34" viewBox="0 0 34 34" style={{flexShrink:0}}><rect width="34" height="34" rx="8" fill="#0D1B3E"/><rect x="5" y="22" width="5" height="9" rx="1.5" fill="white" opacity="0.3"/><rect x="12" y="17" width="5" height="14" rx="1.5" fill="white" opacity="0.55"/><rect x="19" y="11" width="5" height="20" rx="1.5" fill="white" opacity="0.8"/><rect x="26" y="5" width="4" height="26" rx="1.5" fill="white"/></svg><div style={{fontWeight:800,color:N,fontSize:18,letterSpacing:'-0.3px',borderBottom:'2px solid #2563EB',paddingBottom:'1px'}}>TaxStat<span style={{color:B}}>360</span></div></div>)
const T=[
  {n:'Basic',p:'$49',d:'Essential AI tax tools for new S-Corp and LLC owners.',c:'#475569',bg:'#F8FAFC',bd:'#E2E8F0',bBg:'#fff',bC:'#0D1B3E',bBd:'1px solid #E2E8F0',badge:null,cnt:'10 AI Features',features:['IRS Schedule Mapping (C, E, K-1)','Quarterly Tax Payment Planner','Explainable AI Layer','Tax-Saving Opportunity Discovery','Compliance Confidence Indicator','IRS Deadline & Penalty Awareness','IRS-Friendly Language Mode','Depreciation Compliance Engine','Data Confidence Score','AI-Generated Action Plan']},
  {n:'Professional',p:'$99',d:'Advanced planning and compliance tools for growing businesses.',c:'#2563EB',bg:'#EFF6FF',bd:'#2563EB',bBg:'#2563EB',bC:'#fff',bBd:'none',badge:'Most Popular',cnt:'20 AI Features',features:['Everything in Basic, plus:','Real-Time Risk Alert Engine','What-If Scenario Simulator','Advisor & Accountant Collaboration','One-Click CPA Export Pack','Mid-Year Tax & Risk Pulse','Year-Over-Year Intelligence','Financial Data Anomaly Detection','IRS Audit Readiness Mode','State-Level Tax Awareness','Safe Harbor Rule Detection','IRS Rule Change Monitoring','Compliance-Grade AI Guardrails','Industry Benchmark Intelligence','Risk Tolerance Profiling','IRS Data Retention & Audit Trail','AI Assumption Transparency Panel','YOY Intelligence Comparison','Personalized Risk Profiling','Advisor Collaboration Access']},
  {n:'Advanced',p:'$199',d:'The complete 32-feature platform, enterprise-ready and IRS-aligned.',c:'#7C3AED',bg:'#F5F3FF',bd:'#7C3AED',bBg:'#7C3AED',bC:'#fff',bBd:'none',badge:'Full Platform',cnt:'All 32 AI Features',features:['Everything in Professional, plus:','AI Recommendation Change Tracking','Support Replay & Audit Mode','Event-Triggered AI Re-Analysis','Multi-Entity / Multi-Business View','AI-Generated Audit Defense Narrative','Priority Support & Onboarding','Dedicated Account Manager','Custom IRS Correspondence Templates','White-Label Option Available','All 32 AI Features Included']},
]
export default function Landing(){
const nav=useNavigate()
return(<div style={{fontFamily:'Inter,sans-serif',minHeight:'100vh',background:'#F0F4FF'}}>
<nav style={{background:'#fff',borderBottom:'1px solid #E2E8F0',padding:'0 40px',height:64,display:'flex',alignItems:'center',justifyContent:'space-between',position:'sticky',top:0,zIndex:100}}><LOGO/><div style={{display:'flex',gap:12}}><button onClick={()=>nav('/login')} style={{padding:'8px 20px',border:'1px solid #E2E8F0',borderRadius:8,background:'#fff',fontWeight:600,fontSize:14,cursor:'pointer',color:N}}>Sign In</button><button onClick={()=>nav('/signup')} style={{padding:'8px 20px',background:B,color:'#fff',border:'none',borderRadius:8,fontWeight:600,fontSize:14,cursor:'pointer'}}>Get Started Free</button></div></nav>
<div style={{textAlign:'center',padding:'72px 24px 48px'}}><div style={{display:'flex',gap:8,justifyContent:'center',flexWrap:'wrap',marginBottom:16}}><span style={{background:'#EFF6FF',color:B,fontSize:11,fontWeight:700,letterSpacing:1.4,padding:'5px 14px',borderRadius:20}}>AI-BASED AUDIT & RISK PLANNER</span><span style={{background:'#F0FDF4',color:'#15803D',fontSize:11,fontWeight:700,letterSpacing:1.2,padding:'5px 14px',borderRadius:20}}>US-SPECIFIC IRS, STATE & FEDERAL COMPLIANCE</span><span style={{background:'#EFF6FF',color:B,fontSize:11,fontWeight:700,letterSpacing:1.2,padding:'5px 14px',borderRadius:20}}>ADVANCED AI FEATURE EXPANSION</span></div>
<h1 style={{fontSize:52,fontWeight:800,color:N,margin:'0 0 12px',lineHeight:1.1}}>Your Tax Strategy,<br/>Powered by Intelligence</h1>
<p style={{color:SL,fontSize:17,maxWidth:620,margin:'0 auto 32px'}}>TaxStat360 delivers 32 AI-powered features for IRS, state, and federal compliance built for S-Corps, Multi-Member LLCs, and Partnerships.</p>
<div style={{display:'flex',gap:12,justifyContent:'center',flexWrap:'wrap'}}><button onClick={()=>nav('/signup')} style={{padding:'14px 32px',background:B,color:'#fff',border:'none',borderRadius:10,fontWeight:700,fontSize:16,cursor:'pointer'}}>Start Free Trial</button><button onClick={()=>nav('/login')} style={{padding:'14px 32px',background:'#fff',color:N,border:'1px solid #E2E8F0',borderRadius:10,fontWeight:700,fontSize:16,cursor:'pointer'}}>Sign In</button></div></div>
<div style={{background:'#fff',borderTop:'1px solid #E2E8F0',borderBottom:'1px solid #E2E8F0',padding:'24px 40px'}}><div style={{maxWidth:1000,margin:'0 auto',display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:16,textAlign:'center'}}>{[{s:'$100M+',l:'Tax Dollars Saved'},{s:'32',l:'AI-Powered Features'},{s:'10,000+',l:'IRS Schedules Mapped'},{s:'98%',l:'Compliance Rate'}].map(x=>(<div key={x.s}><div style={{fontSize:30,fontWeight:800,color:B,marginBottom:4}}>{x.s}</div><div style={{fontSize:13,color:SL,fontWeight:500}}>{x.l}</div></div>))}</div></div>
<div style={{maxWidth:860,margin:'48px auto',padding:'0 24px'}}><div style={{background:'#fff',borderRadius:16,overflow:'hidden',boxShadow:'0 4px 24px rgba(37,99,235,0.10)',border:'1px solid #E2E8F0'}}><div style={{background:N,padding:'14px 24px',display:'flex',alignItems:'center',gap:8}}><div style={{width:12,height:12,borderRadius:'50%',background:'#ef4444'}}/><div style={{width:12,height:12,borderRadius:'50%',background:'#f59e0b'}}/><div style={{width:12,height:12,borderRadius:'50%',background:'#10b981'}}/><span style={{color:'#94a3b8',fontSize:13,marginLeft:8}}>TaxStat360 Platform Overview</span></div><div style={{position:'relative',paddingBottom:'56.25%',height:0}}><iframe src={'https://player.vimeo.com/video/'+VID+'?badge=0&autopause=0&title=0&byline=0&portrait=0&dnt=1'} title="TaxStat360 Overview" frameBorder="0" allow="autoplay; fullscreen; picture-in-picture" allowFullScreen style={{position:'absolute',top:0,left:0,width:'100%',height:'100%'}}/></div></div></div>
<div style={{background:'#0D1B3E',padding:'64px 24px'}}><div style={{maxWidth:1100,margin:'0 auto'}}><div style={{textAlign:'center',marginBottom:40}}><div style={{display:'inline-block',background:'rgba(37,99,235,0.3)',color:'#93c5fd',fontSize:11,fontWeight:700,letterSpacing:1.5,padding:'6px 14px',borderRadius:20,marginBottom:14}}>SIMPLE, TRANSPARENT PRICING</div><h2 style={{color:'#fff',fontSize:32,fontWeight:800,margin:'0 0 10px'}}>Choose Your AI Tax Intelligence Level</h2><p style={{color:'#94a3b8',fontSize:15,maxWidth:500,margin:'0 auto'}}>Every plan includes a 7-day free trial. No credit card charged until trial ends.</p></div>
<div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:20,alignItems:'start'}}>{T.map(tier=>(<div key={tier.n} style={{background:tier.bg,border:'2px solid '+tier.bd,borderRadius:16,padding:'28px 24px',position:'relative'}}>{tier.badge&&<div style={{position:'absolute',top:-12,left:'50%',transform:'translateX(-50%)',background:tier.c,color:'#fff',fontSize:11,fontWeight:700,padding:'4px 14px',borderRadius:20,whiteSpace:'nowrap'}}>{tier.badge}</div>}
<div style={{textAlign:'center',marginBottom:20}}><div style={{fontWeight:800,color:tier.c,fontSize:13,letterSpacing:1,marginBottom:8}}>{tier.n.toUpperCase()}</div><div style={{display:'flex',alignItems:'baseline',gap:4,justifyContent:'center',marginBottom:6}}><span style={{fontSize:44,fontWeight:800,color:N}}>{tier.p}</span><span style={{color:SL,fontSize:14}}>/mo</span></div><div style={{display:'inline-block',background:tier.c,color:'#fff',fontSize:12,fontWeight:700,padding:'3px 12px',borderRadius:20,marginBottom:12}}>{tier.cnt}</div><div style={{color:SL,fontSize:13,lineHeight:1.5,marginBottom:16}}>{tier.d}</div><button onClick={()=>nav('/signup')} style={{width:'100%',padding:'11px',background:tier.bBg,color:tier.bC,border:tier.bBd,borderRadius:8,fontWeight:700,fontSize:14,cursor:'pointer'}}>Start Free Trial</button></div>
<div style={{borderTop:'1px solid rgba(0,0,0,0.08)',paddingTop:16}}>{tier.features.map((f,i)=>(<div key={i} style={{display:'flex',alignItems:'flex-start',gap:8,marginBottom:8}}><span style={{color:i===0&&f.includes('Everything')?SL:tier.c,fontSize:14,flexShrink:0,fontWeight:700}}>{i===0&&f.includes('Everything')?'':'✓'}</span><span style={{color:i===0&&f.includes('Everything')?SL:N,fontSize:13,lineHeight:1.4,fontWeight:i===0&&f.includes('Everything')?600:400}}>{f}</span></div>))}</div>
</div>))}</div></div></div>
<div style={{background:'#060f1e',padding:'24px',textAlign:'center'}}><p style={{color:'#475569',fontSize:13}}>2025 TaxStat360 · Built by a former IRS Revenue Agent</p></div>
</div>)}
